version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_USER=root 
    networks:
      - node-network

  app:
    build:
      context: ./node
    container_name: app
    tty: true
    networks:
      - node-network    
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx    
    networks:
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge
  